import { NextRequest, NextResponse } from "next/server";
import { jwtDecode } from "jwt-decode";

interface JwtPayload {
  user_id?: string;
  email?: string;
  account_type?: string;
  exp: number;
}

const BACKEND_URL = process.env.BACKEND_SERVICE_URL || "http://avry-backend:8081";

function getAuth(request: NextRequest): { token: string; payload: JwtPayload } | null {
  const token = request.cookies.get("aivory_access_token")?.value;
  if (!token) return null;
  try {
    const payload = jwtDecode<JwtPayload>(token);
    if (payload.exp * 1000 < Date.now()) return null;
    const role = payload.account_type;
    if (role !== "superadmin" && role !== "admin") return null;
    return { token, payload };
  } catch {
    return null;
  }
}

function isSuperAdmin(payload: JwtPayload): boolean {
  return payload.account_type === "superadmin";
}

function generatePassword(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
  let pw = "";
  for (let i = 0; i < 16; i++) pw += chars[Math.floor(Math.random() * chars.length)];
  return pw;
}

export async function POST(request: NextRequest) {
  const auth = getAuth(request);
  if (!auth) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (!isSuperAdmin(auth.payload)) {
    return NextResponse.json({ error: "Forbidden: superadmin only" }, { status: 403 });
  }

  const body = await request.json();
  const { email, password, fullName, autoGeneratePassword } = body;
  if (!email) return NextResponse.json({ error: "Email required" }, { status: 400 });

  const finalPassword = autoGeneratePassword ? generatePassword() : password;
  if (!finalPassword) return NextResponse.json({ error: "Password required" }, { status: 400 });

  try {
    const res = await fetch(`${BACKEND_URL}/api/v1/auth/register`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email,
        password: finalPassword,
        company_name: fullName || email.split("@")[0],
      }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      return NextResponse.json({ error: err.detail || "Failed to create" }, { status: res.status });
    }
    const data = await res.json();
    const userId = data.user?.user_id;

    // Promote to admin via backend
    if (userId) {
      await fetch(`${BACKEND_URL}/api/v1/admin/promote`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${auth.token}` },
        body: JSON.stringify({ user_id: userId, account_type: "admin" }),
      }).catch(() => {});
    }

    return NextResponse.json({
      success: true,
      user: { id: userId, email },
      autoGeneratedPassword: autoGeneratePassword ? finalPassword : undefined,
    });
  } catch (err) {
    return NextResponse.json({ error: "Service unavailable" }, { status: 503 });
  }
}
